export const API_URL = "http://localhost:8080/api";
export const API_IMAGE = "http://localhost:8080/";



export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const ALERT_SUCCESS = "ALERT_SUCCESS";
export const ALERT_ERROR = "ALERT_ERROR";
export const ALERT_CLEAR = "ALERT_CLEAR";
  
export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST';
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL';

export const CATEGORY_DETAILS_REQUEST = 'CATEGORY_DETAILS_REQUEST';
export const CATEGORY_DETAILS_SUCCESS = 'CATEGORY_DETAILS_SUCCESS';
export const CATEGORY_DETAILS_FAIL = 'CATEGORY_DETAILS_FAIL';

export const CATEGORY_CREATE_REQUEST = 'CATEGORY_CREATE_REQUEST';
export const CATEGORY_CREATE_SUCCESS = 'CATEGORY_CREATE_SUCCESS';
export const CATEGORY_CREATE_FAIL = 'CATEGORY_CREATE_FAIL';

export const CATEGORY_UPDATE_REQUEST = 'CATEGORY_UPDATE_REQUEST';
export const CATEGORY_UPDATE_SUCCESS = 'CATEGORY_UPDATE_SUCCESS';
export const CATEGORY_UPDATE_FAIL = 'CATEGORY_UPDATE_FAIL';

export const CATEGORY_DELETE_REQUEST = 'CATEGORY_DELETE_REQUEST';
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS';
export const CATEGORY_DELETE_FAIL = 'CATEGORY_DELETE_FAIL';


export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST';
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS';
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL';

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL';

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_REMOVE_ALL_ITEMS = 'CART_REMOVE_ALL_ITEMS'


export const SUBCATEGORY_LIST_REQUEST = 'SUBCATEGORY_LIST_REQUEST';
export const SUBCATEGORY_LIST_SUCCESS = 'SUBCATEGORY_LIST_SUCCESS';
export const SUBCATEGORY_LIST_FAIL = 'SUBCATEGORY_LIST_FAIL';

export const SUBCATEGORY_DETAILS_REQUEST = 'SUBCATEGORY_DETAILS_REQUEST';
export const SUBCATEGORY_DETAILS_SUCCESS = 'SUBCATEGORY_DETAILS_SUCCESS';
export const SUBCATEGORY_DETAILS_FAIL = 'SUBCATEGORY_DETAILS_FAIL';

export const SUBCATEGORY_CREATE_REQUEST = 'SUBCATEGORY_CREATE_REQUEST';
export const SUBCATEGORY_CREATE_SUCCESS = 'SUBCATEGORY_CREATE_SUCCESS';
export const SUBCATEGORY_CREATE_FAIL = 'SUBCATEGORY_CREATE_FAIL';

export const SUBCATEGORY_UPDATE_REQUEST = 'SUBCATEGORY_UPDATE_REQUEST';
export const SUBCATEGORY_UPDATE_SUCCESS = 'SUBCATEGORY_UPDATE_SUCCESS';
export const SUBCATEGORY_UPDATE_FAIL = 'SUBCATEGORY_UPDATE_FAIL';

export const SUBCATEGORY_DELETE_REQUEST = 'SUBCATEGORY_DELETE_REQUEST';
export const SUBCATEGORY_DELETE_SUCCESS = 'SUBCATEGORY_DELETE_SUCCESS';
export const SUBCATEGORY_DELETE_FAIL = 'SUBCATEGORY_DELETE_FAIL';


//create constants to BUDGET
export const BUDGET_LIST_REQUEST = 'BUDGET_LIST_REQUEST';
export const BUDGET_LIST_SUCCESS = 'BUDGET_LIST_SUCCESS';
export const BUDGET_LIST_FAIL = 'BUDGET_LIST_FAIL';

export const BUDGET_CREATE_REQUEST = 'BUDGET_CREATE_REQUEST';
export const BUDGET_CREATE_SUCCESS = 'BUDGET_CREATE_SUCCESS';
export const BUDGET_CREATE_FAIL = 'BUDGET_CREATE_FAIL';

export const BUDGET_UPDATE_REQUEST = 'BUDGET_UPDATE_REQUEST';
export const BUDGET_UPDATE_SUCCESS = 'BUDGET_UPDATE_SUCCESS';
export const BUDGET_UPDATE_FAIL = 'BUDGET_UPDATE_FAIL';

export const BUDGET_DELETE_REQUEST = 'BUDGET_DELETE_REQUEST';
export const BUDGET_DELETE_SUCCESS = 'BUDGET_DELETE_SUCCESS';
export const BUDGET_DELETE_FAIL = 'BUDGET_DELETE_FAIL';

export const BUDGET_DETAILS_REQUEST = 'BUDGET_DETAILS_REQUEST';
export const BUDGET_DETAILS_SUCCESS = 'BUDGET_DETAILS_SUCCESS';
export const BUDGET_DETAILS_FAIL = 'BUDGET_DETAILS_FAIL';

