export enum Route {
  HOME = "/",
  REGISTER = "/register",
  ADMIN = "/admin",
  CART = "/cart",
  CATEGORY = "/category/:id",
  LOGIN = "/login",
  PRODUCT = "/product/:id",
  PRODUCTS_LIST = "/products",
  PRODUCTS_LIST_SEARCHED = "/products?search=",
  BUDGET = "/budget",
  ADMIN_PRODUCTS = "/admin/products",
  ADMIN_PRODUCTS_CREATE = "/admin/products/create",
  ADMIN_PRODUCTS_EDIT = "/admin/products/edit/:id",
  ADMIN_CATEGORIES = "/admin/categories",
  ADMIN_CATEGORIES_CREATECATEGORY = "/admin/categories/create",
  ADMIN_CATEGORIES_EDIT = "/admin/categories/edit/:id",
  ADMIN_BUDGET = "/admin/budgets",
  NOT_FOUND = "/*",
}
